/**
 * Application Error Codes
 * All error codes are snake_case constants.
 * Grouped by module for easy reference.
 */

module.exports = {
  // ── Auth ──
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_EMAIL_NOT_VERIFIED: 'AUTH_EMAIL_NOT_VERIFIED',
  AUTH_ACCOUNT_SUSPENDED: 'AUTH_ACCOUNT_SUSPENDED',
  AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  AUTH_TOKEN_INVALID: 'AUTH_TOKEN_INVALID',
  AUTH_REFRESH_TOKEN_INVALID: 'AUTH_REFRESH_TOKEN_INVALID',
  AUTH_REFRESH_TOKEN_EXPIRED: 'AUTH_REFRESH_TOKEN_EXPIRED',
  AUTH_OTP_INVALID: 'AUTH_OTP_INVALID',
  AUTH_OTP_EXPIRED: 'AUTH_OTP_EXPIRED',
  AUTH_OTP_MAX_ATTEMPTS: 'AUTH_OTP_MAX_ATTEMPTS',
  AUTH_EMAIL_EXISTS: 'AUTH_EMAIL_EXISTS',
  AUTH_INVALID_EMAIL_DOMAIN: 'AUTH_INVALID_EMAIL_DOMAIN',
  AUTH_WEAK_PASSWORD: 'AUTH_WEAK_PASSWORD',
  AUTH_UNAUTHORIZED: 'AUTH_UNAUTHORIZED',
  AUTH_FORBIDDEN: 'AUTH_FORBIDDEN',
  AUTH_GOOGLE_FAILED: 'AUTH_GOOGLE_FAILED',

  // ── User ──
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_PROFILE_INCOMPLETE: 'USER_PROFILE_INCOMPLETE',
  USER_ALREADY_TUTOR: 'USER_ALREADY_TUTOR',

  // ── Tutor ──
  TUTOR_NOT_FOUND: 'TUTOR_NOT_FOUND',
  TUTOR_PROFILE_EXISTS: 'TUTOR_PROFILE_EXISTS',
  TUTOR_NOT_VERIFIED: 'TUTOR_NOT_VERIFIED',
  TUTOR_UNAVAILABLE: 'TUTOR_UNAVAILABLE',

  // ── Booking ──
  BOOKING_NOT_FOUND: 'BOOKING_NOT_FOUND',
  BOOKING_SLOT_UNAVAILABLE: 'BOOKING_SLOT_UNAVAILABLE',
  BOOKING_SLOT_CONFLICT: 'BOOKING_SLOT_CONFLICT',
  BOOKING_INSUFFICIENT_CREDITS: 'BOOKING_INSUFFICIENT_CREDITS',
  BOOKING_CANNOT_BOOK_SELF: 'BOOKING_CANNOT_BOOK_SELF',
  BOOKING_ALREADY_CANCELLED: 'BOOKING_ALREADY_CANCELLED',
  BOOKING_CANNOT_CANCEL: 'BOOKING_CANNOT_CANCEL',
  BOOKING_LATE_CANCELLATION: 'BOOKING_LATE_CANCELLATION',

  // ── Session ──
  SESSION_NOT_FOUND: 'SESSION_NOT_FOUND',
  SESSION_NOT_ACTIVE: 'SESSION_NOT_ACTIVE',
  SESSION_ALREADY_COMPLETED: 'SESSION_ALREADY_COMPLETED',
  SESSION_GROUP_FULL: 'SESSION_GROUP_FULL',

  // ── Wallet ──
  WALLET_NOT_FOUND: 'WALLET_NOT_FOUND',
  WALLET_INSUFFICIENT_BALANCE: 'WALLET_INSUFFICIENT_BALANCE',
  WALLET_TRANSACTION_FAILED: 'WALLET_TRANSACTION_FAILED',
  WALLET_NEGATIVE_BALANCE: 'WALLET_NEGATIVE_BALANCE',

  // ── Review ──
  REVIEW_NOT_FOUND: 'REVIEW_NOT_FOUND',
  REVIEW_ALREADY_EXISTS: 'REVIEW_ALREADY_EXISTS',
  REVIEW_SESSION_NOT_COMPLETED: 'REVIEW_SESSION_NOT_COMPLETED',
  REVIEW_NOT_PARTICIPANT: 'REVIEW_NOT_PARTICIPANT',

  // ── Subject ──
  SUBJECT_NOT_FOUND: 'SUBJECT_NOT_FOUND',
  SUBJECT_ALREADY_EXISTS: 'SUBJECT_ALREADY_EXISTS',

  // ── Notification ──
  NOTIFICATION_NOT_FOUND: 'NOTIFICATION_NOT_FOUND',

  // ── Admin ──
  ADMIN_ACTION_FAILED: 'ADMIN_ACTION_FAILED',
  ADMIN_USER_NOT_FOUND: 'ADMIN_USER_NOT_FOUND',

  // ── Group Sessions ──
  GROUP_SESSION_NOT_AVAILABLE: 'GROUP_SESSION_NOT_AVAILABLE',
  GROUP_SESSION_ALREADY_JOINED: 'GROUP_SESSION_ALREADY_JOINED',
  GROUP_SESSION_NOT_PARTICIPANT: 'GROUP_SESSION_NOT_PARTICIPANT',
  GROUP_SESSION_ALREADY_STARTED: 'GROUP_SESSION_ALREADY_STARTED',

  // ── AI ──
  AI_ENGINE_UNAVAILABLE: 'AI_ENGINE_UNAVAILABLE',
  AI_MATCH_FAILED: 'AI_MATCH_FAILED',

  // ── File Upload ──
  FILE_TOO_LARGE: 'FILE_TOO_LARGE',
  FILE_INVALID_TYPE: 'FILE_INVALID_TYPE',
  FILE_UPLOAD_FAILED: 'FILE_UPLOAD_FAILED',

  // ── General ──
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
};
